--[[

██╗  ██╗ █████╗ ████████╗███████╗██████╗     ██╗  ██╗██╗   ██╗██████╗ 
██║ ██╔╝██╔══██╗╚══██╔══╝██╔════╝██╔══██╗    ██║  ██║██║   ██║██╔══██╗
█████╔╝ ███████║   ██║   █████╗  ██████╔╝    ███████║██║   ██║██████╔╝
██╔═██╗ ██╔══██║   ██║   ██╔══╝  ██╔══██╗    ██╔══██║██║   ██║██╔══██╗
██║  ██╗██║  ██║   ██║   ███████╗██║  ██║    ██║  ██║╚██████╔╝██████╔╝
╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝   ╚══════╝╚═╝  ╚═╝    ╚═╝  ╚═╝ ╚═════╝ ╚═════╝   


Its the thing that you can see on the side of the script!
]]

{
    [1] = "100%!",
    [2] = "Holy cow, man!",
    [3] = "Pixels!",
    [4] = "Flashing letters!",
    [5] = "May contain deez nuts!",
    [6] = "Polish cow!",
    [7] = "Just a bunch of codes!",
    [8] = "Its Lit!",
    [9] = "Classic!",
    [10] = "discord.gg/",
    [11] = "Discord!",
    [12] = "ScriptBlox!",
    [13] = "More splashtags!",
    [14] = "Funny!",
    [15] = "Only Scripts!",
    [16] = "Lua!",
    [17] = "Fuck Joe Biden!",
    [18] = "Near WWIII!",
    [19] = "were is Ukraine?",
    [20] = "Call of Duty - WW3!",
    [21] = "Grand theft auto VI!",
    [22] = "Exploits",
    [23] = "Roblox Porn!",
    [24] = "☢Radio Active☢!",
    [25] = "⚡Electro⚡!",
    [26] = "🔐 100% Safe!",
    [27] = "👑King of the hill!",
    [28] = "Cool!",
    [29] = "Colin4President!"
}
